{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todo-app.frontend.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.frontend.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
