{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "todo-app.fullname" . }}-backend
subjects:
- kind: ServiceAccount
  name: {{ include "todo-app.backend.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
