{{- if .Values.serviceAccount.create -}}
{{- if .Values.mcpServer.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todo-app.mcpServer.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.mcpServer.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
